# Generated by Django 6.0.1 on 2026-02-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_donationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequest',
            name='blood_group',
        ),
    ]
